core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('news/post/<int:year>/<int:month>/<int:day>/<slug:post>', views.PostDetails, name='Post_Details'),
    path('news/', views.AllPosts, name='All_Posts')
]

new_epafos/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('core.urls', namespace='core')),
    path('', include('news.urls', namespace='news')),
    path('', include('exercises.urls', namespace='exercises')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'news'

urlpatterns = [
    path('manager/createpost/', views.CreatePost, name='Create_Post'),
    path('manager/editpost/<int:id>',views.EditPost, name='Edit_Post'),
    path('manager/manageposts/', views.ManagePosts, name='Manage_Posts'),
    path('manager/post/<int:year>/<int:month>/<int:day>/<slug:post>', views.ManagerPostDetails, name='Manager_Post_Details'),
    path('schoolnews/post/<int:year>/<int:month>/<int:day>/<slug:post>', views.PostDetails, name='Post_Details'),
    path('teacher/schoolnews/', views.SchoolPosts, name='Teacher_News'),
    path('student/schoolnews/', views.SchoolPosts, name='Student_News'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.utils import timezone
from accounts.models import SchoolUser
from django_ckeditor_5.fields import CKEditor5Field
from django.urls import reverse

class Post(models.Model):
  class Categories(models.TextChoices):
    STUDENTSHIP = 'Studentship', 'Studentship'
    EOPEP = 'EOPEP', 'Eopep Examinations'
    EXAMINATIONS = 'EXAMS', 'Examinations'
  
  class Status(models.TextChoices):
    DRAFT = 'Draft', 'Draft'
    PUBLISHED = 'Published', 'Published'

  title = models.CharField(max_length=255)
  category = models.CharField(max_length=15,
                              choices=Categories.choices,
                              default=Categories.STUDENTSHIP)
  slug = models.SlugField(max_length=255, unique_for_date='published')
  author = models.ForeignKey(SchoolUser,
                            on_delete=models.CASCADE,
                            related_name='news')
  body = CKEditor5Field(config_name='extends')
  published = models.DateTimeField(default=timezone.now)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  status = models.CharField(max_length=10,
                            choices=Status.choices,
                            default=Status.DRAFT)

  class Meta:
    ordering = ['-published']
    indexes = [ 
          models.Index(fields=['-published']),
        ]
  
  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return reverse('core:Post_Details', args=[self.published.year,
                                              self.published.month,
                                              self.published.day,
                                              self.slug])
  def news_get_absolute_url(self):
      return reverse('news:Post_Details', args=[self.published.year,
                                                self.published.month,
                                                self.published.day,
                                                self.slug])
  def manager_get_absolute_url(self):
      return reverse('news:Manager_Post_Details', args=[self.published.year,
                                                self.published.month,
                                                self.published.day,
                                                self.slug])
  

news/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from .models import Post
from accounts.models import SchoolUser

class NewPost(forms.ModelForm):
  category = forms.ChoiceField(choices=Post.Categories.choices, widget=forms.Select(attrs={'class': 'form-select w-25', 'id': 'category_field'}))
  status = forms.ChoiceField(choices=Post.Status.choices, widget=forms.Select(attrs={'class': 'form-select w-25', 'id': 'status_field'}))
  body = forms.CharField(widget=CKEditor5Widget(config_name='extends'), required=False)
  class Meta:
    model = Post
    fields = ('title','category', 'slug', 'body', 'status')
    widgets = {
      'title' : forms.TextInput(attrs={'class': 'form-control w-50', 'id': 'post_title'}),
      'slug' : forms.TextInput(attrs={'class': 'form-control', 'id': 'post_slug '}),
    }

class EditSchoolPost(forms.ModelForm):
  category = forms.ChoiceField(choices=Post.Categories.choices, widget=forms.Select(attrs={'class': 'form-select w-25', 'id': 'category_field'}))
  status = forms.ChoiceField(choices=Post.Status.choices, widget=forms.Select(attrs={'class': 'form-select w-25', 'id': 'status_field'}))
  body = forms.CharField(widget=CKEditor5Widget(config_name='extends'), required=False)
  class Meta:
    model = Post
    fields = ('title', 'category', 'slug', 'body','status')
    widgets = {
      'title' : forms.TextInput(attrs={'class': 'form-control w-50', 'id': 'post_title'}),
      'slug' : forms.TextInput(attrs={'class': 'form-control', 'id': 'post_slug '}),
    }

news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .forms import NewPost, EditSchoolPost
from .models import Post
from accounts.views import manager_required

@manager_required
def CreatePost(request):
  if request.method == 'POST':
    post_form = NewPost(request.POST)
    if post_form.is_valid():
      post = post_form.save(commit=False)
      post.author = request.user
      post.published = timezone.now()
      post.save()
      return redirect('core:Home')
  else:
    post_form = NewPost()
  return render(request, 'manager/addpost.html', {'post_form':post_form})

@manager_required
def EditPost(request, id):
  post = get_object_or_404(Post, id=id)
  if request.method == 'POST':
    post_form = EditSchoolPost(request.POST, instance=post)
    if post_form.is_valid():
      post_form.save()
      return redirect('news:Manager_Post_Details', post.published.year, post.published.month, post.published.day, post.slug)
  else:
    post_form = EditSchoolPost(instance=post)
  return render(request, 'manager/editpost.html',{'post':post, 
                                                       'post_form':post_form})  

@manager_required
def ManagerPostDetails(request, year, month, day, post):
  post = get_object_or_404(Post, 
                          slug = post,
                          published__year = year,
                          published__month = month, 
                          published__day = day)

  return render(request, 'manager/details.html', {'post':post})

@login_required
def PostDetails(request, year, month, day, post):
  post = get_object_or_404(Post, 
                          status=Post.Status.PUBLISHED,
                          slug = post,
                          published__year = year,
                          published__month = month, 
                          published__day = day)

  return render(request, 'news/details.html', {'post':post})

@manager_required
def ManagePosts(request):
  all_posts = Post.objects.all()
  categories = Post.Categories.choices
  selected_category = request.GET.get('category', 'all')
  
  if selected_category != 'all':
    posts = Post.objects.filter(category=selected_category)
  
  else:
    posts = all_posts
  return render(request, 'manager/manageposts.html', {'posts':posts, 
                                                           'categories':categories})

@login_required
def SchoolPosts(request):
  posts = Post.objects.filter(status=Post.Status.PUBLISHED)
  if request.user.role == 'Teacher':
    return render(request, 'teacher/teachernews.html',{'posts':posts})
  elif request.user.role == 'Student':
    return render(request, 'student/studentnews.html',{'posts':posts})

news/templates/manager/addpost.html
{% extends 'managerDash.html' %}

{% block title %}Create a post {% endblock %}
{% block header %}
    {{ post_form.media }}
{% endblock %}
{% block content %}
<div class="container p-4 main-content">
  <button onclick="history.go(-1); return false;" class="btn btn-secondary float-end">Go back</button>
    <h2>Compose a new Post</h2>
    <form method="POST" action="{% url 'news:Create_Post' %}">
        {% csrf_token %}
        {{ post_form.as_p }}
        <button type="submit" class="btn btn-primary">Upload Article</button>
    </form>
</div>
{% endblock %}

news/templates/manager/details.html
{% extends 'managerDash.html' %}

{% block title %}Edit Post {{post.name}} {% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <div class="p-2 float-end">
    <a href="{% url 'news:Edit_Post' post.id %}" class="btn btn-primary">Edit</a>
    <button onclick="history.go(-2); return false;" class="btn btn-secondary">Go back</button>
  </div>
  <h3>{{post.title}}</h3>
  <p class="text-muted">{{post.category}} - {{post.published}}</p>
  <p>{{post.body|safe}}</p>
</div>
{% endblock %}

news/templates/manager/editpost.html
{% extends 'managerDash.html' %}

{% block title %} Edit Post {{post.title}} {% endblock %}

{% block header %}
  {{post_form.media}}
{% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <h2>Edit Post</h2>
  <form method="POST">
    {% csrf_token %}
    {{post_form.as_p}}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
  </div>
{% endblock %}

news/templates/manager/manageposts.html
{% extends 'managerDash.html' %}
{% load static %}

{% block title %}News {% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <h3>Manage Posts</h3>
  <p>You are now viewing {{posts.category}}</p>
  <div class="d-flex justify-content-between">
    <form method="GET" action="{% url 'news:Manage_Posts' %}">
      <div class="d-flex">      
        <select name="category" class="form-select" style="width:150px;">
          <option value="all">Show All</option>
          {% for value, name in categories %}
            <option value="{{ value }}">{{ name }}</option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-secondary">Filter</button>
      </div>
    </form>
    <a href="{% url 'news:Create_Post' %}" class="btn btn-primary">Create new Post</a>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Post</th>
        <th scope="col">Title</th>
        <th scope="col">Category</th>
        <th scope="col">Slug</th>
        <th scope="col">Body</th>
        <th scope="col">Uploaded</th>
        <th scope="col">Updated</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
        <td><a href="{{post.manager_get_absolute_url}}">{{ post.id }}</a></td>
        <td>{{ post.title }}</td>
        <td>{{ post.category}}</td>
        <td>{{ post.slug }}</td>
        <td>{{ post.body|safe|truncatewords:5 }}</td>
        <td>{{ post.created }}</td>
        <td>{{ post.updated }}</td>
        <td>{{ post.status }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}