accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterUser, name='Register_User'),
    path('addstudentdata/<int:id>', views.AddStudentData, name='Add_Student_Data'),
    path('addteacherdata/<int:id>', views.AddTeacherData, name='Add_Teacher_Data'),
    path('login/', views.Login, name='Login'),
    path('logout/', views.Logout, name='Logout'),
    path('manager/manageusers/', views.ManageUsers, name='Manage_Users'),
    path('manager/manageuser/<int:id>', views.UserDetails, name='User_Details'),
    path('manager/edituser/<int:id>', views.EditUser, name='Edit_User'),
    path('manager/deleteuser/<int:id>', views.DeleteUser, name='Delete_User'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('news/post/<int:year>/<int:month>/<int:day>/<slug:post>', views.PostDetails, name='Post_Details'),
    path('news/', views.AllPosts, name='All_Posts')
]

new_epafos/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('core.urls', namespace='core')),
    path('', include('news.urls', namespace='news')),
    path('', include('exercises.urls', namespace='exercises')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from dashboard.models import Major

class SchoolUser(AbstractUser):
  id = models.AutoField(primary_key=True)
  first_name = models.CharField(max_length=100)
  last_name = models.CharField(max_length=100)
  birthdate = models.DateField(blank=True, auto_now_add=False, null=True)
  role = models.CharField(max_length=20, choices={'Teacher':'Teacher', 'Student':'Student', 'Manager':'Manager'})
  phone_number = models.CharField(max_length=10)
  address = models.CharField(max_length=100, null=True)

class EnrolledStudent(models.Model):
  def get_majors():
    return [(major.name , major.name) for major in Major.objects.all()]
  student_id = models.CharField(max_length=4, primary_key=True)
  user = models.OneToOneField(SchoolUser, on_delete=models.CASCADE)
  major = models.ForeignKey(Major, on_delete=models.CASCADE)
  def __str__(self):
    return self.student_id

class Teacher(models.Model):
  teacher_id = models.CharField(max_length=10, primary_key=True)
  user = models.OneToOneField(SchoolUser, on_delete=models.CASCADE)
  occupation = models.CharField(max_length=100)
  def __str__(self):
    return self.teacher_id

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import EnrolledStudent, Major, Teacher
from .models import SchoolUser
import datetime

class SchoolUserCreationForm(UserCreationForm):
  password1 = forms.CharField(min_length=8,
                              widget=forms.PasswordInput(attrs={'class':'form_field form-control',
                                                                'id':'pass1_field',
                                                                'placeholder':'enter users password'}))
  password2 = forms.CharField(min_length=8, widget=forms.PasswordInput(attrs={'class':'form_field form-control',
                                                                              'id':'pass2_field',
                                                                              'placeholder':'enter users password again'}))
  class Meta(UserCreationForm):
    model = SchoolUser
    fields = (
      'role',
      'username',
      'password1',
      'password2',
      'email',
      'first_name',
      'last_name',
      'phone_number',
      'birthdate',
      'address'
    )  
    yearCalc = (int(datetime.datetime.now().strftime("%Y"))-17)
    widgets = {
      'username' : forms.TextInput(attrs={'class':'form_field form-control',
                                        'id':'user_field',
                                        'placeholder':'enter username'}),
      'email' : forms.EmailInput(attrs={'class':'form_field form-control',
                                        'id':'email_field',
                                        'placeholder':'enter users email address'}),
      'first_name' : forms.TextInput(attrs={'class':'form_field form-control',
                                            'id':'first_name',
                                            'placeholder':'enter users firstname'}),
      'last_name' : forms.TextInput(attrs={'class':'form_field form-control',
                                           'id':'last_name',
                                           'placeholder':'enter users lastname'}),
      'phone_number' : forms.TextInput(attrs={'class':'form_field form-control ',
                                              'id':'phone_field',
                                              'placeholder':'enter users phone number'}),
      'birthdate' : forms.SelectDateWidget(years=range(1940,yearCalc),
                                           attrs={'class':'date_widget form-select w-25', 
                                                  'id':'birthdate_field'}),
      'address' : forms.TextInput(attrs={'class':'form-field form-control',
                                         'id':'address_field',
                                         'placeholder':'enter users address'})
    } 

class SchoolUserChangeForm(UserChangeForm):
  class Meta:
    model = SchoolUser
    fields = UserChangeForm.Meta.fields
  
class LoginForm(forms.Form):
  username = forms.CharField(max_length=100,
                            required=True, 
                            widget=forms.TextInput(attrs={'class':'form_field form-control',
                                                          'id':'user_field',
                                                          'placeholder':'enter username'}))
  password = forms.CharField(min_length=8,
                            widget=forms.PasswordInput(attrs={'class':'form_field form-control',
                                                              'id':'pass1_field',
                                                              'placeholder':'enter users password'}))
  class Meta:
    model = SchoolUser
    fields = ('username', 'password')

class StudentDataForm(forms.ModelForm):
  major = forms.ModelChoiceField(queryset=Major.objects.all(), widget=forms.Select(attrs={'class':'select-form'}))
  class Meta:
    model = EnrolledStudent
    fields = ('student_id', 'major') 
    widgets = {
      'student_id' : forms.TextInput(attrs={'placeholder':'enter students id',
                                                                          'class':'form-control student_id_field', 
                                                                          'id':'studentID',
                                                                          'max_length':'4'})
    }

class TeacherDataForm(forms.ModelForm):
  class Meta:
    model = Teacher
    fields = ('teacher_id', 'occupation')
    widgets = {
      'teacher_id' : forms.TextInput(attrs={'placeholder':'enter teachers id',
                                                          'class':'form-control teacher_id_field',
                                                          'id':'teacherID',
                                                          'maxlength':'10'}),
      'occupation' : forms.TextInput(attrs={'placeholder':'enter users occupation',
                                                                'class':'form-control occupation_field',
                                                                'id':'occupation'})                                 
    }

class EditSchoolUser(UserChangeForm):
  username = forms.CharField(widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'username_field', 'placeholder':'enter users username'}), required=False)
  email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form_field form-control w-50', 'id':'email_field', 'placeholder':'enter users email address'}), required=False)
  first_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'first_name', 'placeholder':'enter users firstname'}))
  last_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'last_name', 'placeholder':'enter users lastname'}))
  phone_number = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'phone_field', 'placeholder':'enter users phone number'}), required=False)
  address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-field form-control w-50', 'id':'address_field','placeholder':'enter users address'}), required=False)

  class Meta:
    model = SchoolUser
    fields = ('email','username','first_name','last_name','phone_number','address')
  
class EditStudentData(forms.ModelForm):
  major = forms.ModelChoiceField(queryset=Major.objects.all(), required=False)
  class Meta:
    model = EnrolledStudent
    fields = ('major',)

class EditTeacherData(forms.ModelForm):
  class Meta:
    model = Teacher
    fields = ('occupation',)
    widgets = {
      'occupation' : forms.TextInput(attrs = {'placeholder':'enter user occupation',
                                            'class':'form-control occupation_field w-50',
                                            'id':'occupation'}),
    }
  

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SchoolUserCreationForm, LoginForm
from .models import SchoolUser 
from .models import EnrolledStudent, Teacher
from . import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from dashboard.views import manager_required

def Login(request):
  form = LoginForm()
  if request.method == 'POST':
    form = LoginForm(request.POST)
    if form.is_valid():
      username = form.cleaned_data.get('username')
      password = form.cleaned_data.get('password')
      user = authenticate(request, username=username, password=password)
      if user is not None:
        login(request, user)
        if user.role == 'Student':
          return redirect('dashboard:Student_Home')
        elif user.role == 'Teacher':
          return redirect('dashboard:Teacher_Home')
        elif user.role == 'Manager':
          return redirect('dashboard:Manager_Home')
  return render(request, 'login.html', {'form':form})

@login_required
@manager_required
def RegisterUser(request):
  if request.user.is_staff:
    if request.method == 'POST':
      form = SchoolUserCreationForm(request.POST)
      if form.is_valid():
        user = form.save()
        if user.role == 'Student':
          return redirect('accounts:Add_Student_Data', user.id)
        elif user.role == 'Teacher':
          return redirect('accounts:Add_Teacher_Data', user.id)
    else:
      form = SchoolUserCreationForm()

    return render(request, 'register.html', {'form':form})

def AddStudentData(request, id):
  user = get_object_or_404(SchoolUser, id=id)
  if request.method == 'POST':
    student_form = forms.StudentDataForm(request.POST)
    if student_form.is_valid():
      new_student = EnrolledStudent.objects.create(
          user = user,
          major = student_form.cleaned_data['major'],
          student_id = student_form.cleaned_data['student_id']
      )
      new_student.save()
      return redirect('accounts:Manage_Users')
    return render(request, 'userDataRegister/add_user_data.html', {'user':user,
                                                                  'student_form':student_form})
  return render(request, 'userDataRegister/user_data.html', {'user':user})

def AddTeacherData(request, id):
  user = get_object_or_404(SchoolUser, id=id)
  if request.method == 'POST':
    teacher_form = forms.TeacherDataForm(request.POST)
    if teacher_form.is_valid():
      new_teacher = Teacher.objects.create(
        user = user,
        teacher_id = teacher_form.cleaned_data['teacher_id'],
        occupation = teacher_form.cleaned_data['occupation']
      )
      new_teacher.save()
      return redirect('accounts:Manage_Users')
    return render(request, 'userDataRegister/add_user_data.html', {'user':user,
                                                                  'teacher_form':teacher_form})
  return render(request, 'userDataRegister/user_data.html', {'user':user})

def Logout(request):
  logout(request)
  return redirect('accounts:Login')

@login_required
@manager_required
def ManageUsers(request):
  all_users = SchoolUser.objects.all()
  roles = SchoolUser.objects.values_list('role', flat=True).distinct()
  selected_role = request.GET.get('role', 'all')

  if selected_role != 'all':
    users = SchoolUser.objects.filter(role=selected_role)
  else:
    users = all_users

  return render(request, 'manageusers/users.html', {
                                                'roles':roles,
                                                'users':users,
                                                'selected_role':selected_role})

def UserDetails(request, id):
  user = get_object_or_404(SchoolUser, id=id)
  return render(request, 'manageusers/details.html', {'user':user})

@login_required
@manager_required
def EditUser(request, id):
  user = get_object_or_404(SchoolUser, id=id)
  teacher = Teacher.objects.get(user=user)if user.role == 'Teacher' else None
  student = EnrolledStudent.objects.get(user=user)if user.role == 'Student' else None
  if request.method == 'POST':
    form = forms.EditSchoolUser(request.POST, instance=user)
    teacher_data = forms.EditTeacherData(request.POST, instance=teacher)if user.role == 'Teacher' else None
    student_data = forms.EditStudentData(request.POST, instance=student)if user.role == 'Student' else None
    if user.role == 'Student':
      if form.is_valid() and student_data.is_valid():
          form.save()
          student_data.save()
          return redirect('accounts:User_Details', user.id)
    elif user.role == 'Teacher':
      if form.is_valid() and teacher_data.is_valid():
          form.save()
          teacher_data.save()
          return redirect('accounts:User_Details', user.id)
    else: 
      if form.is_valid():
        form.save()
        return redirect('accounts:User_Details', user.id)
  else:
    form = forms.EditSchoolUser(instance=user)
    teacher_data = forms.EditTeacherData(instance=teacher)if user.role == 'Teacher' else None
    student_data = forms.EditStudentData(instance=student)if user.role == 'Student' else None
    
  return render(request, 'manageusers/edituser.html', {'form':form,
                                                  'student_data':student_data,
                                                  'teacher_data':teacher_data, 
                                                  'user':user})
@manager_required
def DeleteUser(request, id):
  user = SchoolUser.objects.get(id=id)
  if request.method == 'POST':
      user.delete()
      return redirect('accounts:Manage_Users')
  
  return render(request, 'manageusers/deleteuser.html',{'user':user})

accounts/templates/manageusers/deleteuser.html
{% extends 'managerDash.html' %}
{% load static %}

{% block title %} Confirm User Deletion {% endblock %}

{% block content %}
<div class="container p-4">
<h2>Are you sure you want to delete the user {{user.username}}</h2>
<p>This user is a {{user.role}}</p>
  <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete User" class="btn btn-danger">
    <button onclick="history.go(-1); return false;" class="btn btn-secondary">No take me back</button>
  </form>
</div>
{% endblock %}

accounts/templates/manageusers/details.html
{% extends 'managerDash.html' %}
{% load static %}

{% block title %}{{user.first_name}} {{user.last_name}} {% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <button onclick="goBackAndRefresh();" class="btn btn-secondary float-end">Go back</button>
  <div class="col-lg-8">
    <h4>Personal Info</h4>
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Full Name</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.first_name}} {{user.last_name}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Email</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.email}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Username</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.username}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Phone</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.phone_number}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Address</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.address}}</p>
          </div>
        </div>
      </div>
    </div>
</div>
{% if user.role == 'Student' %}
<div class="col-lg-8">
  <h4>Student Info</h4>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Student ID</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.enrolledstudent.student_id}}</p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Major</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.enrolledstudent.major}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% elif user.role == 'Teacher' %}
<div class="col-lg-8">
  <h4>Teacher Info</h4>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Teacher ID</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.teacher.teacher_id}}</p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Major</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.teacher.occupation}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
<a href="{% url 'accounts:Edit_User' user.id %}" class="btn btn-primary">Edit User</a>
{% endblock %}

accounts/templates/manageusers/edituser.html
{% extends 'managerDash.html' %}
{% load static %}

{% block title %}{{user.first_name}} {{user.last_name}} {% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <button onclick="history.go(-1); return false;" class="btn btn-secondary float-end">Go back</button>
<form method="POST">
  {% csrf_token %}
  <div class="col-lg-8">
    <h3>Edit Profile of {{user.first_name}} {{user.last_name}}</h3>
    <hr>
    <h4>Personal Info</h4>
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">First Name</p>
          </div>
          <div class="col-sm-9 d-flex justify-content-between">
            <p class="text-muted mb-0">{{user.first_name}}</p>
            {{ form.first_name }}
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Last Name</p>
          </div>
          <div class="col-sm-9 d-flex justify-content-between">
            <p class="text-muted mb-0">{{user.last_name}}</p>
            {{ form.last_name }}
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Email</p>
          </div>
          <div class="col-sm-9 d-flex justify-content-between">
            <p class="text-muted mb-0">{{user.email}}</p>
            {{ form.email }}
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Username</p>
          </div>
          <div class="col-sm-9 d-flex justify-content-between">
            <p class="text-muted mb-0">{{user.username}}</p>
            {{ form.username }}
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Phone</p>
          </div>
          <div class="col-sm-9 d-flex justify-content-between">
            <p class="text-muted mb-0">{{user.phone_number}}</p>
            {{ form.phone_number }}
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Address</p>
          </div>
          <div class="col-sm-9 d-flex justify-content-between">
            <p class="text-muted mb-0">{{user.address}}</p>
            {{ form.address }}
          </div>
        </div>
      </div>
    </div>
</div>
{% if user.role == 'Student' %}
<div class="col-lg-8">
  <h4>Student Info</h4>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Student ID</p>
        </div>
        <div class="col-sm-9 d-flex justify-content-between">
          <p class="text-muted mb-0">{{user.enrolledstudent.student_id}}</p>
          {% comment %} {{student_data.student_id}} {% endcomment %}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Major</p>
        </div>
        <div class="col-sm-9 d-flex justify-content-between">
          <p class="text-muted mb-0">{{user.enrolledstudent.major}}</p>
          {{student_data.major}}
        </div>
      </div>
    </div>
  </div>
</div>
{% elif user.role == 'Teacher' %}
<div class="col-lg-8">
  <h4>Teacher Info</h4>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Teacher ID</p>
        </div>
        <div class="col-sm-9 d-flex justify-content-between">
          <p class="text-muted mb-0">{{user.teacher.teacher_id}}</p>
          {% comment %} {{teacher_data.teacher_id}} {% endcomment %}
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Occupation</p>
        </div>
        <div class="col-sm-9 d-flex justify-content-between">
          <p class="text-muted mb-0">{{user.teacher.occupation}}</p>
          {{teacher_data.occupation}}
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
<button type="submit" class="btn btn-primary">Save</button>
<a href="{% url 'accounts:Delete_User' user.id %}" class="btn btn-danger">Delete User</a>
</form>
</div>
{% endblock %}

accounts/templates/manageusers/users.html
{% extends 'managerDash.html' %}
{% load static %}

{% block title %}Users {% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <h3>Manage Users</h3>
  <p>You are now viewing {{selected_role}}s</p>
  <div class="d-flex justify-content-between">
    <form method="GET" action="{% url 'accounts:Manage_Users' %}">
      <div class="d-flex">      
        <select name="role" class="form-select" style="width:150px;">
          <option value="all">Show All</option>
          {% for role in roles %}
            <option value="{{ role }}">{{ role }}</option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-secondary">Filter</button>
      </div>
    </form>
    <a href="{% url 'accounts:Register_User' %}" class="btn btn-primary">Add User</a>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Username</th>
        <th scope="col">Role</th>
        {% if selected_role == 'Student' %}
        <th scope="col">Major</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td><a href="{% url 'accounts:User_Details' user.id %}">{{ user.id }}</a></td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.role }}</td>
        {% if selected_role == 'Student' %}
        <td>{{ user.enrolledstudent.major }}</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}