accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterUser, name='Register_User'),
    path('addstudentdata/<int:id>', views.AddStudentData, name='Add_Student_Data'),
    path('addteacherdata/<int:id>', views.AddTeacherData, name='Add_Teacher_Data'),
    path('login/', views.Login, name='Login'),
    path('logout/', views.Logout, name='Logout'),
    path('manager/manageusers/', views.ManageUsers, name='Manage_Users'),
    path('manager/manageuser/<int:id>', views.UserDetails, name='User_Details'),
    path('manager/edituser/<int:id>', views.EditUser, name='Edit_User'),
    path('manager/deleteuser/<int:id>', views.DeleteUser, name='Delete_User'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('news/post/<int:year>/<int:month>/<int:day>/<slug:post>', views.PostDetails, name='Post_Details'),
    path('news/', views.AllPosts, name='All_Posts')
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('manager/', views.ManagerHome, name='Manager_Home'),
    path('student/', views.StudentHome, name='Student_Home'),
    path('teacher/', views.TeacherHome, name='Teacher_Home'),
]

new_epafos/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('core.urls', namespace='core')),
    path('', include('news.urls', namespace='news')),
    path('', include('exercises.urls', namespace='exercises')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.shortcuts import render, get_object_or_404
from news.models import Post

def Home(request):
  latest_posts = Post.objects.filter(status=Post.Status.PUBLISHED)[:3]

  return render(request, 'index.html', {'latest_posts': latest_posts})

def PostDetails(request, year, month, day, post):
  post = get_object_or_404(Post, 
                          status=Post.Status.PUBLISHED,
                          slug = post,
                          published__year = year,
                          published__month = month, 
                          published__day = day)
  recent_posts = Post.objects.filter(status= Post.Status.PUBLISHED, category = post.category).exclude(id=post.id)[:3]

  return render(request, 'core/news/details.html', {'post':post, 
                                                    'recent_posts':recent_posts})

def AllPosts(request):
  posts = Post.objects.filter(status=Post.Status.PUBLISHED)

  return render(request, 'core/news/news.html', {'posts':posts})

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %} {% endblock %} | Schools Name</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <style>
    #flowDetect{
      outline: 1px solid red;
    }

    @media(min-width:989px){
      #recentNews{
        position:static;
      }
    }
  </style>
</head>

<body>
  {% load static %}
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <div class="navbar-brand">
        <img src="{% static 'images/logo.png' %}" alt="logo of the school" style="width: 40px; height: 40px;">
        <a class="navbar-brand align-middle" href="#">Schools Name</a>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:Home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:All_Posts' %}">News</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Our school</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact Us</a>
          </li>
        </ul>
        <div>
          {% if request.user.is_authenticated and user.role == 'Manager' %}
          <a href="{% url 'dashboard:Manager_Home' %}" class="btn btn-primary">E-school</a>
          {% elif request.user.is_authenticated and user.role == 'Student' %}
          <a href="{% url 'dashboard:Student_Home' %}" class="btn btn-primary">E-school</a>
          {% elif request.user.is_authenticated and user.role == 'Teacher' %}
          <a href="{% url 'dashboard:Teacher_Home' %}" class="btn btn-primary">E-school</a>
          {% else %}
          <a href="{% url 'accounts:Login' %}" class="btn btn-primary">E-school</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  {% block content %}

  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
{% comment %} Hero Section {% endcomment %}
<div class="px-4 pt-5 my-5 text-center border-bottom">
  <h1 class="display-4 fw-bold text-body-emphasis">School Name</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
      sed do eiusmod tempor incididunt ut labore et 
      dolore magna aliqua. Ut enim ad minim veniam, 
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    </p>
  </div>
  <div style="max-height: 60vh;">
    <div class="container px-5">
      <img src="{% static 'images/school.jpg' %}" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
    </div>
  </div>
</div>

{% comment %} Recent news {% endcomment %}
<div class="container">
  <h2>Recent News</h2>
  <div class="row mb-2">
    {% for post in latest_posts %}
    <div class="col-md-4" style="height: 300px;">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative" style="height: 250px;">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">{{post.category}}</strong>
          <h3 class="mb-0">{{post.title}}</h3>
          <div class="mb-1 text-body-secondary">{{post.published}}</div>
          <p class="card-text mb-auto">{{post.body|safe}}</p>
          <a href="{{ post.get_absolute_url }}" class="icon-link gap-1 icon-link-hover stretched-link">
            Continue reading
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}