accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterUser, name='Register_User'),
    path('addstudentdata/<int:id>', views.AddStudentData, name='Add_Student_Data'),
    path('addteacherdata/<int:id>', views.AddTeacherData, name='Add_Teacher_Data'),
    path('login/', views.Login, name='Login'),
    path('logout/', views.Logout, name='Logout'),
    path('manager/manageusers/', views.ManageUsers, name='Manage_Users'),
    path('manager/manageuser/<int:id>', views.UserDetails, name='User_Details'),
    path('manager/edituser/<int:id>', views.EditUser, name='Edit_User'),
    path('manager/deleteuser/<int:id>', views.DeleteUser, name='Delete_User'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('news/post/<int:year>/<int:month>/<int:day>/<slug:post>', views.PostDetails, name='Post_Details'),
    path('news/', views.AllPosts, name='All_Posts')
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('manager/', views.ManagerHome, name='Manager_Home'),
    path('student/', views.StudentHome, name='Student_Home'),
    path('teacher/', views.TeacherHome, name='Teacher_Home'),
]

new_epafos/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('accounts.urls')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('core.urls', namespace='core')),
    path('', include('news.urls', namespace='news')),
    path('', include('exercises.urls', namespace='exercises')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

class Major(models.Model):
  name = models.CharField(max_length=255)
  description = models.TextField()
  def __str__(self):
    return self.name

dashboard/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from .models import EnrolledStudent, Major, Teacher
from accounts.models import SchoolUser
from django.contrib.auth.forms import UserChangeForm

class StudentDataForm(forms.ModelForm):
  major = forms.ModelChoiceField(queryset=Major.objects.all(), widget=forms.Select(attrs={'class':'select-form'}))
  class Meta:
    model = EnrolledStudent
    fields = ('student_id', 'major') 
    widgets = {
      'student_id' : forms.TextInput(attrs={'placeholder':'enter students id',
                                                                          'class':'form-control student_id_field', 
                                                                          'id':'studentID',
                                                                     'max_length':'4'})
    }

class TeacherDataForm(forms.ModelForm):
  class Meta:
    model = Teacher
    fields = ('teacher_id', 'occupation')
    widgets = {
      'teacher_id' : forms.TextInput(attrs={'placeholder':'enter teachers id',
                                                          'class':'form-control teacher_id_field',
                                                          'id':'teacherID',
                                                          'maxlength':'10'}),
      'occupation' : forms.TextInput(attrs={'placeholder':'enter users occupation',
                                                                'class':'form-control occupation_field',
                                                                'id':'occupation'})                                 
    }

class EditSchoolUser(UserChangeForm):
  username = forms.CharField(widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'username_field', 'placeholder':'enter users username'}), required=False)
  email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form_field form-control w-50', 'id':'email_field', 'placeholder':'enter users email address'}), required=False)
  first_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'first_name', 'placeholder':'enter users firstname'}))
  last_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'last_name', 'placeholder':'enter users lastname'}))
  phone_number = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class':'form_field form-control w-50', 'id':'phone_field', 'placeholder':'enter users phone number'}), required=False)
  address = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-field form-control w-50', 'id':'address_field','placeholder':'enter users address'}), required=False)

  class Meta:
    model = SchoolUser
    fields = ('email','username','first_name','last_name','phone_number','address')
  
class EditStudentData(forms.ModelForm):
  major = forms.ModelChoiceField(queryset=Major.objects.all(), required=False)
  class Meta:
    model = EnrolledStudent
    fields = ('major',)

class EditTeacherData(forms.ModelForm):
  class Meta:
    model = Teacher
    fields = ('occupation',)
    widgets = {
      'occupation' : forms.TextInput(attrs = {'placeholder':'enter user occupation',
                                            'class':'form-control occupation_field w-50',
                                            'id':'occupation'}),
      # 'teacher_id' : forms.TextInput(attrs = {'placeholder':'enter teachers id',
      #                                       'class':'form-control teacher_id_field w-50',
      #                                       'id':'teacherID'})
    }
  

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from functools import wraps

def manager_required(view_func):
  @wraps(view_func)
  def _wrapped_view(request, *args, **kwargs):
    if request.user.is_authenticated and request.user.role == 'Manager':
        return view_func(request, *args, **kwargs)
    return redirect('Login')
  return _wrapped_view

def student_required(view_func):
  @wraps(view_func)
  def _wrapped_view(request, *args, **kwargs):
    if request.user.is_authenticated and request.user.role == 'Student':
        return view_func(request, *args, **kwargs)
    return redirect('Login')
  return _wrapped_view

def teacher_required(view_func):
  @wraps(view_func)
  def _wrapped_view(request, *args, **kwargs):
    if request.user.is_authenticated and request.user.role == 'Teacher':
        return view_func(request, *args, **kwargs)
    return redirect('Login')
  return _wrapped_view

@login_required
@manager_required
def ManagerHome(request):
  return render(request, 'manager/home.html')

@login_required
@student_required
def StudentHome(request):
  return render(request, 'student/home.html')

@login_required
@teacher_required
def TeacherHome(request):
  return render(request, 'teacher/home.html')




    

dashboard/templates/manager/users/details.html
{% extends 'managerDash.html' %}
{% load static %}

{% block title %}{{user.first_name}} {{user.last_name}} {% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <button onclick="goBackAndRefresh();" class="btn btn-secondary float-end">Go back</button>
  <div class="col-lg-8">
    <h4>Personal Info</h4>
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Full Name</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.first_name}} {{user.last_name}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Email</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.email}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Username</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.username}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Phone</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.phone_number}}</p>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <p class="mb-0">Address</p>
          </div>
          <div class="col-sm-9">
            <p class="text-muted mb-0">{{user.address}}</p>
          </div>
        </div>
      </div>
    </div>
</div>
{% if user.role == 'Student' %}
<div class="col-lg-8">
  <h4>Student Info</h4>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Student ID</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.enrolledstudent.student_id}}</p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Major</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.enrolledstudent.major}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% elif user.role == 'Teacher' %}
<div class="col-lg-8">
  <h4>Teacher Info</h4>
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Teacher ID</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.teacher.teacher_id}}</p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0">Major</p>
        </div>
        <div class="col-sm-9">
          <p class="text-muted mb-0">{{user.teacher.occupation}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
<a href="{% url 'dashboard:Edit_User' user.id %}" class="btn btn-primary">Edit User</a>
{% endblock %}

dashboard/templates/manager/users/users.html
{% extends 'managerDash.html' %}
{% load static %}

{% block title %}Users {% endblock %}

{% block content %}
<div class="container p-4 main-content">
  <h3>Manage Users</h3>
  <p>You are now viewing {{selected_role}}s</p>
  <div class="d-flex justify-content-between">
    <form method="GET" action="{% url 'dashboard:Manage_Users' %}">
      <div class="d-flex">      
        <select name="role" class="form-select" style="width:150px;">
          <option value="all">Show All</option>
          {% for role in roles %}
            <option value="{{ role }}">{{ role }}</option>
          {% endfor %}
        </select>
        <button type="submit" class="btn btn-secondary">Filter</button>
      </div>
    </form>
    <a href="{% url 'Register_User' %}" class="btn btn-primary">Add User</a>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Username</th>
        <th scope="col">Role</th>
        {% if selected_role == 'Student' %}
        <th scope="col">Major</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td><a href="{% url 'dashboard:User_Details' user.id %}">{{ user.id }}</a></td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.role }}</td>
        {% if selected_role == 'Student' %}
        <td>{{ user.enrolledstudent.major }}</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}